# dbt/profiles.yml
analytics_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      port: 5432
      dbname: cricket_stats
      schema: analytics
      threads: 4
      keepalives_idle: 0
