version: 2

models:
  - name: stg_match_details
    description: "Staging model that extracts match-specific details from raw data."
    columns:
      - name: series_name
        description: "The name of the series."
      - name: match_number
        description: "Match number in the series."
      - name: match_type
        description: "Type of the match (ODI, Test, etc.)."
      - name: venue
        description: "Venue where the match was played."
      - name: toss_winner
        description: "The team that won the toss."
      - name: toss_decision
        description: "The decision made by the team that won the toss."
      - name: winner
        description: "The team that won the match."
