name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dbt
        run: |
          pip install dbt-postgres

      - name: Run dbt
        run: dbt run --profiles-dir dbt/
